# Mounting Google Drive

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive

# Move to the Dataset Directory in My Drive

In [ ]:
import os
os.chdir("/gdrive/My Drive/Machine Learning (HPL) - MITACS 2025")
!pwd

/gdrive/My Drive/Machine Learning (HPL) - MITACS 2025

# Obtenain stats from unique features from the chosen models

## Import libraries

In [ ]:
import numpy as np
import pandas as pd

## Load Excel File with the stats

In [ ]:
path_stats = 'Sample Data/Multivars_stats_older.xlsx'

df_stats = pd.read_excel(path_stats, header=None)
df_stats = df_stats.transpose()
df_stats.columns = df_stats.loc[0][:]
df_stats = df_stats.loc[1:][:]
df_stats.head()

,Variable Name,Moment_A1S,Moment_A1S,Moment_A1S_time,Moment_A1S_time,Power_A2S,Power_A2S,Power_A2S_time,Power_A2S_time,Moment_H1S,...,S2V_TO,S2V_TO,V2G_HS,V2G_HS,V2G_OTO,V2G_OTO,V2G_OHS,V2G_OHS,V2G_TO,V2G_TO
1,Group,Control,Flatfoot,Control,Flatfoot,Control,Flatfoot,Control,Flatfoot,Control,...,Control,Flatfoot,Control,Flatfoot,Control,Flatfoot,Control,Flatfoot,Control,Flatfoot
2,Mean,1.310128,1.28532,48.877934,49.097274,2.792139,2.657019,56.047257,56.33891,0.658675,...,2.408389,1.663336,-14.578109,-17.531826,2.840327,1.009753,13.711759,13.014393,63.660639,63.545457
3,Std Deviation,0.118309,0.184612,1.495727,1.867169,0.618505,0.697535,0.919998,1.685783,0.15318,...,7.235086,5.768866,5.257705,4.772427,3.850249,3.013035,5.356774,8.23057,8.660639,10.435255
4,Median,1.312405,1.280985,48.799065,49.310911,2.836865,2.546135,56.0,56.584715,0.621315,...,2.507145,0.940795,-13.786985,-17.06473,2.39815,1.44865,11.444395,10.771495,60.05069,60.771055
5,Biomodality coefficient,0.414652,0.248349,0.326226,0.35329,0.365429,0.440538,0.352706,0.286194,0.595579,...,0.324958,0.31558,0.317347,0.358755,0.441553,0.187021,0.545045,0.421231,0.49625,0.422264

## Load the excel file with the unique features

In [ ]:
path_invariant = 'Sample Data/Unique_features_older.xlsx'
#path_variant   = 'Unique_features_variant.xlsx'

Excel_invariant = pd.ExcelFile(path_invariant)
#Excel_variant   = pd.ExcelFile(path_variant)

In [ ]:
unique_ft_stats_invariant = {}
#unique_ft_stats_variant = {}

In [ ]:
stats_columns = df_stats.iloc[:,0]
stats_columns

1                       Group
2                        Mean
3               Std Deviation
4                      Median
5     Biomodality coefficient
6           Normality p-value
7           Normality W-value
8                 T-test pval
9            MannWhitney pval
10                  Hist_bin1
11                  Hist_bin2
12                  Hist_bin3
13                  Hist_bin4
14                  Hist_bin5
15                  Hist_bin6
16                  Hist_bin7
17                  Hist_bin8
18                  Hist_bin9
19                 Hist_bin10
Name: Variable Name, dtype: object

In [ ]:
for sheet_name in Excel_invariant.sheet_names:
    df_unique_ft = pd.read_excel(Excel_invariant, sheet_name=sheet_name)
    unique_ft = df_unique_ft['Feature_Name']
    temp_df_stats = df_stats[unique_ft]
    unique_ft_stats_invariant[sheet_name] = temp_df_stats.set_index(stats_columns).transpose()

In [ ]:
for sheet_name in Excel_variant.sheet_names:
    df_unique_ft = pd.read_excel(Excel_variant, sheet_name=sheet_name)
    unique_ft     = df_unique_ft['Feature_Name']
    temp_df_stats = df_stats[unique_ft]
    unique_ft_stats_variant[sheet_name] = temp_df_stats.set_index(stats_columns).transpose()

In [ ]:
# Save all filtered sheets to a new Excel file
with pd.ExcelWriter('Feature_stats_older.xlsx') as writer:
    for sheet_name, df_filtered in unique_ft_stats_invariant.items():
        df_filtered.to_excel(writer, sheet_name=sheet_name, index=True)

In [ ]:
# Save all filtered sheets to a new Excel file
with pd.ExcelWriter('Feature_stats_variant.xlsx') as writer:
    for sheet_name, df_filtered in unique_ft_stats_variant.items():
        df_filtered.to_excel(writer, sheet_name=sheet_name, index=True)